image: golang:latest

before_script:
  - go get -d -v

test:
  dependencies: []
  script:
    - go test ./...

build:win64:
  stage: build
  variables:
    GOOS: windows
    GOARCH: amd64
  script:
    - go build -o comfy-translator.exe
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
    - comfy-translator.exe

build:linux64:
  stage: build
  variables:
    GOOS: linux
    GOARCH: amd64
  script:
    - go build -o comfy-translator
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
    - comfy-translator

build:osx:
  stage: build
  variables:
    GOOS: darwin
    GOARCH: amd64
  script:
    - go build -o comfy-translator
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
    - comfy-translator
