image: golang:latest

variables:
  BIN_NAME: comfy-translator
  ARTIFACTS_DIR: artifacts
  GO_PROJECT:  gitgud.io/softashell/comfy-translator
  OUTPUT_PATH: ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/${BIN_NAME}

before_script:
  - mkdir -p ${GOPATH}/src/${GO_PROJECT}
  - mkdir -p ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}
  - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/
  - cd ${GOPATH}/src/${GO_PROJECT}
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

test:
  dependencies: []
  script:
    - go test ./...

build:win64:
  stage: build
  variables:
    GOOS: windows
    GOARCH: amd64
  script:
    - go build -o ${OUTPUT_PATH}.exe
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - ${ARTIFACTS_DIR}

build:linux64:
  stage: build
  variables:
    GOOS: linux
    GOARCH: amd64
  script:
    - go build -o ${OUTPUT_PATH}
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - ${ARTIFACTS_DIR}

build:osx:
  stage: build
  variables:
    GOOS: darwin
    GOARCH: amd64
  script:
    - go build -o ${OUTPUT_PATH}
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - ${ARTIFACTS_DIR}
