[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/coreos/bbolt"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-retryablehttp"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

  [[constraint]]
  branch = "master"
  name = "github.com/davecgh/go-spew"

[prune]
  go-tests = true
  unused-packages = true
